name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - ipywidgets
  - IPython
  - seaborn
  - scikit-learn
  - xlrd
  - pip:
    - xgboost
    - shap
